### ISSUE TITLE
At runtime a lot of DLL's are being fetched...

### ISSUE THREAD

**Issue by Niek42** [elgransan/BlazorWasmWithNetFrameworkMVC#2]
Hi Santiago,

your repo worked like a charm, but my own implementation did not. It's quite a complicated and large old MVC application, where a small part is replaced by a wasm component.
As far as I can see everything is done like your example, but on running the mvc app I get loads of Internal Server errors in the Developer Tool's Network tab. They are all errors concerning fetches of dll's. I checked your examples and your example doesn't fetch any dll's (as it shouldn't indeed).
Do you have any idea why my app is fetching all those dll's?
Thanks in advance!
![blazor_wasm_mvc_errors1](https://github.com/elgransan/BlazorWasmWithNetFrameworkMVC/assets/81151186/b0a9e4da-fcca-4303-b5dc-8458d2cd3620)

**Comment by elgransan** [comment]
Hi, all those dll must be downloaded from the server for sure, because blazor wasm runs on the client and it need its.

Did you add on your web.config this rules:
![image](https://github.com/elgransan/BlazorWasmWithNetFrameworkMVC/assets/9949584/cdc08cd2-4c7d-4fde-a92f-edaad8106ed4)

Or can you show me the real error (it says error 500 server error)

**Comment by Niek42** [comment]
Hi, thanks for your quick reply.

 

I did add those web.config rules, I checked it again …

 

The error in the Network tab of Chrome:

 



 

The errors in the Console output in VS2022:

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:41094)

    at preRun (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:41082)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:5:96601)

    at wc (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:5:96593)

    --- await ---

    at e.preRun (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:5:95528)

    at callRuntimeCallbacks (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:16437)

    at preRun (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:11876)

    at run (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:142508)

    at runCaller (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:142385)

    at removeRunDependency (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:13105)

    at receiveInstance (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:14994)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:5:96025)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:45898)

    --- await ---

    at instantiateWasm (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:45904)

    at mc (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:5:95983)

    at e.instantiateWasm (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:5:95482)

    at createWasm (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:16104)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\dotnet.7.0.12.jfevxxi2k4.js:14:119437)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39951)

    --- await ---

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

   at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

Uncaught TypeError TypeError: Failed to fetch

    at loadResourceWithoutCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:52251)

    at loadResourceWithCaching (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:51982)

    --- Promise.then ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39163)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:39140)

    at start (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:46018)

    at Vt (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:62202)

    --- await ---

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63609)

    at <anonymous> (D:\Source\Repos\GOconnectIT\Click-App\KlicApp\KlicApp.Web\_framework\blazor.webassembly.js:1:63686)

 

Van: elgransan ***@***.***> 
Verzonden: vrijdag 20 oktober 2023 21:13
Aan: elgransan/BlazorWasmWithNetFrameworkMVC ***@***.***>
CC: Niek42 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [elgransan/BlazorWasmWithNetFrameworkMVC] At runtime a lot of DLL's are being fetched... (Issue #2)

 

Hi, all those dll must be downloaded from the server for sure, because blazor wasm runs on the client and it need its.

Did you add on your web.config this rules:
 <https://user-images.githubusercontent.com/9949584/277031638-cdc08cd2-4c7d-4fde-a92f-edaad8106ed4.png> 

Or can you show me the real error (it says error 500 server error)
